### ISSUE TITLE
Change heading "aidan" to "introduction"

### ISSUE THREAD

**Issue by aidan-parkinson** [aidan-parkinson/anonymous-feedback#12]

**Comment by li3097** [comment]
![image](https://user-images.githubusercontent.com/12212385/96812232-20e3b100-13ea-11eb-9846-e0e7638a1b26.png)

I was trying to find the file in here but cannot seem to find it. The screenshot shows what it would look like as I edited it in dev tools but its just saved to my browser and not where you want it.

**Comment by li3097** [comment]
I just found it in this file: anonymous-feedback/anonymous-feedback/src/components/practical/practical.js  LINE 27

**Comment by aidan-parkinson** [comment]
New introduction section added. Team might expand, so name for this section is fine I think
